apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://192.168.1.150:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    access: proxy
    url: http://192.168.1.150:3100
    editable: false

  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://192.168.1.150:9093
    editable: false
